/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 9.0.2
board: MIMXRT1170-EVK
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_FXOSInitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_FXOSInitPins:
- options: {callFromInitBoot: 'true', coreID: cm4, enableClock: 'true'}
- pin_list:
  - {pin_num: D9, peripheral: LPI2C3, signal: SCL, pin_signal: GPIO_DISP_B2_10, software_input_on: Enable, open_drain: Enable, drive_strength: Normal}
  - {pin_num: A6, peripheral: LPI2C3, signal: SDA, pin_signal: GPIO_DISP_B2_11, software_input_on: Enable, open_drain: Enable, drive_strength: Normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_FXOSInitPins, assigned for the Cortex-M4F core.
 * Description   : configure i2c5 pin for FXOS8700 ecompass sensor
 *
 * END ****************************************************************************************************************/
void BOARD_FXOSInitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_10_LPI2C3_SCL,      /* GPIO_DISP_B2_10 is configured as LPI2C3_SCL */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_DISP_B2_10 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_DISP_B2_11_LPI2C3_SDA,      /* GPIO_DISP_B2_11 is configured as LPI2C3_SDA */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_DISP_B2_11 */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_10_LPI2C3_SCL,      /* GPIO_DISP_B2_10 PAD functional properties : */
      0x14U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_DISP_B2_11_LPI2C3_SDA,      /* GPIO_DISP_B2_11 PAD functional properties : */
      0x14U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Enable
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
